language: node_js
version: 1.0
jobs:
  include:
    - stage: Build and Test
      script:
        - yarn build
        - yarn test
    - stage: Release
      script: yarn build
      deploy:
        edge: true
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^v[0-9]+.*$/
